version: "3"

services:

  proxy:
    container_name: proxy
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./includes:/etc/nginx/includes
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/ssl/certs/nginx
    networks:
      - proxy_network

networks:
  proxy_network: