version: "3"

services:

  proxy:
    image: nginx
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./includes:/etc/nginx/includes
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/ssl/certs/nginx
    networks:


networks:
