version: "3"

services:

  proxy:
    image: nginx
    container_name: proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./includes:/etc/nginx/includes
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/ssl/certs/nginx
    networks:

networks:
